---
### TO CHECK: Do we need consul-template?

- name: Provision MariaDB container image
  hosts: packer

  vars_files:
    # Control node configuration
    - "{{ playbook_dir }}/../../../ryo-control-node/configuration/configuration.yml"
    # Host configuration
    - "{{ playbook_dir }}/../../../ryo-host/configuration/configuration_{{ host_id }}.yml"
    # Module configuration
    - "{{ playbook_dir }}/../../configuration/configuration.yml"

  roles:
    - role: upgrade-container
    - role: install-iptables
    - role: install-cron
    - role: install-mariadb
    - role: install-consul

#    - role: install-unzip
#    - role: install-consul-template

    - role: set-up-firewall
    - role: set-up-mariadb

    # - role: set-up-mariadb-common
    # - role: set-up-mariadb-bootstrap
    # - role: set-up-mariadb-node


    - role: set-up-consul

#    - role: set-up-consul-template
