---
# Add signing key
#
- name: Add MariaDB signing key
  apt_key:
    keyserver: 'keyserver.ubuntu.com'
    id: '0xF1656F24C74CD1D8'
    state: present

# OLD VERSION - REMOVE AFTER TESTING WITH THE ABOVE
# - name: Add MariaDB signing key
#   apt_key:
#     url: https://mariadb.org/mariadb_release_signing_key.asc
#     state: present

# Add repository
#
- name: Set up MariaDB repositories
  apt_repository:
    repo: 'deb [arch=amd64,arm64,ppc64el] http://archive.mariadb.org/mariadb-{{ mariadb_version }}/repo/ubuntu/ focal main'
    state: present
    update_cache: yes

# Install packages
- name: Install MariaDB packages
  apt:
    name:
    - mariadb-common
    - mariadb-server
    - mariadb-client
    - mariadb-backup
    update_cache: yes
    state: present
