#-----------------------
# REQUIRED Configuration
#-----------------------

# Basic module configuration
#---------------------------

# Do not change this unless you know what you are doing 
module_id: ryo-mariadb
mariadb_ip_addr_host_part: 12
